sonar.projectKey=sonar-node-app
sonar.projectName=Sonar Node App
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=squ_0c5b53aeeb5aa854589cb86ac5803568f481a4ba
